### ISSUE TITLE
[ISSUE]  Pagination doesn't work - unable to fetch all data

### ISSUE THREAD

**Issue by martinkiska** [zscaler/zscaler-sdk-python#197]
zpa.server_groups.list_groups() doesn't return all configured server group as described in function description. Instead it follows default pagezise=20 and page=1 and returns only 20 values. It looks to me that pagination is not working and function is unable to roll over all data.

https://github.com/zscaler/zscaler-sdk-python/blob/668f1e5c25fa84e2979238d4f05b25bf1317f2a7/zscaler/zpa/server_groups.py#L36

```
        a = self.zpa.server_groups.list_groups(pagesize=500)
        b = self.zpa.server_groups.list_groups()
        print (f"Size of 'a' with customized pagesize {len(a)}")
        print (f"Size of 'b' with customized pagesize {len(b)}")
```

Output:
```
Size of 'a' with customized pagesize 22
Size of 'b' with customized pagesize 20
```

While debugging it further. Issues seems to be with L505
https://github.com/zscaler/zscaler-sdk-python/blob/668f1e5c25fa84e2979238d4f05b25bf1317f2a7/zscaler/zpa/__init__.py#L505

you expect there "nextPage" in dict, but in real that is not returned from API server, due to that I am unable to fetch all data from the server and process it:

![image](https://github.com/user-attachments/assets/14653a3a-1658-4577-83a0-4bc4dc1c8aec)

**Comment by kvzonrise** [comment]
Hello, the same issue apply for list_users

**Comment by martinkiska** [comment]
> Hello, the same issue apply for list_users

Yep, I agree - issue is in underlying get_paginated_data() function, which is being used by all the other functions. So pagination will not work in every function.

**Comment by willguibr** [comment]
@martinkiska / @kvzonrise  Please take a look at the following branch [zpa-#199-fix/fixed-complex-condition-template](https://github.com/zscaler/zscaler-sdk-python/tree/zpa-%23199-fix/fixed-complex-condition-template) compile the code, and try the pagination again.
Once you confirm it's working, we'll put out a new minor release out.

Zscaler DevRel

**Comment by martinkiska** [comment]
Hi @willguibr,
thanks for quick response. I was checking it and pagination still doesn't work. I can see that you increased default size of pagesize to 500, it was working for our 429 production segments. To overcome the number I randomly generated 100+ app segments so currently I have more than 500 (exactly 534).

![image](https://github.com/user-attachments/assets/535763ca-fa46-46c0-9db9-a6edda547ca4)

As nextPage key doesn't exist in the response, this if statement is not working
![image](https://github.com/user-attachments/assets/10d32122-698d-4b47-862a-d1629db23ca5)

Probably if you replace this line with below code it will start working - https://github.com/zscaler/zscaler-sdk-python/blob/d5991ab80bcd0be152f3f8e639c286089618e41c/zscaler/zpa/__init__.py#L512 I tested it with pagesize=20 and I was able to roll over all app segments

```
                if int(params.get("page")) < int(response_data.get("totalPages")):
                    next_page = int(params.get("page"))+1
```

**Comment by willguibr** [comment]
@martinkiska / @kvzonrise 
We have pushed a new adjustment, to the custom pagination for both ZPA and ZIA.
Please test and let us know if that fixes the issue you've reported.
Thank you

Zscaler DevRel.

**Comment by kvzonrise** [comment]
Hello,
I was able to test the package with ZIA  and to get users/departments/groups. At least the parameter pagesize (without _) is working and I can get up to 1000 entries, but the paging still does not work. 
The weird thing is that is working without an underscore and if I reference it with an underscore then i get an exception "unexpected keyword argument". If I try with max_pages with or without underscore, I also get unexpected keyword argument.

**Comment by willguibr** [comment]
@kvzonrise Please make sure you're pulling the latest changes from the branch: [zpa-#199-fix/fixed-complex-condition-template](https://github.com/zscaler/zscaler-sdk-python/tree/zpa-%23199-fix/fixed-complex-condition-template) as previously indicated. The correct argument is `pagesize`, which is the native argument expected in the API. `max_pages` and `max_items` are custom parameters not native to the API, and must be provided in snake_case format.
```py
for user in zia.users.list_users(max_pages=1, max_items=10):
    pprint(user)
```

```py
for user in zia.users.list_users(page=1, pagesize=10):
    pprint(user)
```
Please confirm if this is working, and we'll issue a new minor release.

Zscaler DevRel.

**Comment by martinkiska** [comment]
Hi @willguibr,
while checking pagination with ZPA part of SDK I am able to pull all data from ZPA. I tested it with 534 app segments and max pagesize=500, and also with forced pagesize=20 I was able to roll over 27 pages. I am also good with closing this issues from my side.
